name: Python CI/CD

on:
  push:
    branches:
      - main   # Trigger on pushes to the 'main' branch
  pull_request:
    branches:
      - main   # Trigger on pull requests to 'main'

jobs:
  test:
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'   # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt   # Install dependencies

    - name: Run tests
      run: |
        python -m unittest discover   # Run Python tests

  deploy:
    needs: test    # Deploy only if tests are successful
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Server
      run: |
        echo "Deploy step. Add deployment commands here."
